### ISSUE TITLE
new release/tag?

### ISSUE THREAD

**Issue by TimB87** [sepen/portdbc#1]
Hi sepen!

I am just taking over opt/portdbc and noticed that it now reports back as version 1.2 instead of 1.1.
Is there any chance you can make a tag for it? :-)

Thanks
Tim

**Comment by sepen** [comment]
Hey Tim!

Sorry for the delay in replying and many thanks for your work maintaining this for CRUX.

Perhaps I have not understood your question well. Release `1.2` already exists and when I went from `1.1` to `1.2` what I did was basically move the code to github and apply the changes (https://github.com/sepen/portdbc/commit/34344396dfa5c7e5de96fea8137d27129affdfaf) that are in the _fixups.patch_ file to have HTTPS support, so you can safely remove this file _fixups.patch_ from _opt/portdbc_.

Tell me if I can do something else

Regards

**Comment by TimB87** [comment]
Good morning sepen :coffee: 

Seems like I just didn't look correctly. You are right, there is already a tag for `1.2`. Sorry! I am closing this now :-)

Have a great weekend!
